sudo: required
services:
    - docker

before_install:
    - docker build -t ravishk17/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ravishk17/docker-react npm run test

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-1"
#     app: "docker"
#     env: "Docker-env"
#     bucket_name: "elasticbeanstalk-us-east-1-684483971995"
#     bucket_path: "docker"
#     on:
#         branch: master
        

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY