sudo: required
services:
    - docker

before_install:
    - docker build -t ravishk17/partypros -f Dockerfile.dev .

script:
    - docker run -e CI=true ravishk17/partypros npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "partypros"
    env: "Partypros-env"
    bucket_name: "elasticbeanstalk:us-east-2:119094900355"
    bucket_path: "partypros"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY